# Site settings
title: TraktApiSharp
email: henrik.froehling@gmail.com
description: A .NET wrapper library for the Trakt.tv API.
twitter_username: henrikfroehling
github_username:  henrikfroehling

baseurl: "/TraktApiSharp"
permalink: pretty

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# Content
collections:
  homePageExamples:
