# Site settings
title: TraktApiSharp
email: henrik.froehling@gmail.com
description: ""
twitter_username: henrikfroehling
github_username:  henrikfroehling

baseurl: "/TraktApiSharp"

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
